apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: payments-routes
spec:
  hosts:
    - reviews.com
  http:
    - route:
        - destination:
            host: payments
            subset: v1
          weight: 65
        - destination:
            host: payments
            subset: v2
          weight: 35
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: payments-destination
spec:
  host: payments
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
