apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: notification-service-ap
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: notification-service
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/default/sa/booking-service-account"]
      to:
        - operation:
            methods: ["POST"]
    - to:
        - operation:
            methods: ["POST"]