apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: notification
  namespace: default
spec:
  hosts:
    - notification-service
  http:
    - route:
        - destination:
            host: notification-service
            subset: v1
      fault:
        abort:
          percentage:
            value: 100
          httpStatus: 500
